apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-svc
spec:
  selector:
    matchLabels:
      app: auction-svc
  template:
    metadata:
      labels:
        app: auction-svc
    spec:
      containers:
      - name: auction-svc
        image: karalinskidavid/microservicestestproject/auction-svc:latest
        imagePullPolicy: Never
        env:
          - name: RabbitMq__Host
            valueFrom: 
              configMapKeyRef:
                name: auction-configmap
                key: RabbitMq__Host
          - name: RabbitMq__User
            valueFrom:
              configMapKeyRef:
                name: auction-configmap
                key: RabbitMq__User
          - name: RabbitMq__Password
            valueFrom:
              configMapKeyRef:
                name: auction-configmap
                key: RabbitMq__Password
          - name: ConnectionStrings__AuctionsDb
            valueFrom:
              configMapKeyRef:
                name: auction-configmap
                key: ConnectionStrings__AuctionsDb
          - name: Kestrel__Endpoints__Grpc__Protocols
            value: Http2
          - name: Kestrel__Endpoints__Grpc__Url
            value: http://+:7777
          - name: Kestrel__Endpoints__WebApi__Protocols
            value: Http1
          - name: Kestrel__Endpoints__WebApi__Url
            value: http://+:80
          - name: AzureAdB2C__Instance
            valueFrom: 
              configMapKeyRef:
                name: auction-configmap
                key: AzureAdB2C__Instance
          - name: AzureAdB2C__ClientId
            valueFrom: 
              configMapKeyRef:
                name: auction-configmap
                key: AzureAdB2C__ClientId
          - name: AzureAdB2C__Domain
            valueFrom: 
              configMapKeyRef:
                name: auction-configmap
                key: AzureAdB2C__Domain
          - name: AzureAdB2C__SignUpSignInPolicyId
            valueFrom: 
              configMapKeyRef:
                name: auction-configmap
                key: AzureAdB2C__SignUpSignInPolicyId