services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopwd 
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15673:15672
  auction-svc:
    image: karalinskidavid/microservicestestproject/auction-svc:latest
    build: 
      context: .
      dockerfile: ./src/Services/AuctionService/Dockerfile
    ports:
      - 7001:80
      - 7777:7777
    env_file:
      - ./src/Services/AuctionService/.env
    depends_on:
      - postgres
      - rabbitmq
  bid-svc:
    image: karalinskidavid/microservicestestproject/bid-svc:latest
    build: 
      context: .
      dockerfile: ./src/Services/BidService/Dockerfile
    ports:
      - 7003:80
    env_file:
      - ./src/Services/BidService/.env
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    image: karalinskidavid/microservicestestproject/search-svc:latest
    build: 
      context: .
      dockerfile: ./src/Services/SearchService/Dockerfile
    ports:
      - 7002:80
    env_file:
      - ./src/Services/SearchService/.env
    depends_on:
      - mongodb
      - rabbitmq
  gateway-svc:
    image: karalinskidavid/microservicestestproject/gateway-svc:latest
    build: 
      context: .
      dockerfile: ./src/Services/GatewayService/Dockerfile
    ports:
      - 6001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientAppUrl=http://localhost:3000
      - AzureAdB2C__Instance=https://microservicestestproject.b2clogin.com
      - AzureAdB2C__Domain=microservicestestproject.onmicrosoft.com
      - AzureAdB2C__ClientId=58eeaf89-f86a-4179-9fd0-b5565fbd54c6
      - AzureAdB2C__SignUpSignInPolicyId=B2C_1_microservicestestproject_signup_singnin
  notification-svc:
    image: karalinskidavid/microservicestestproject/notification-svc:latest
    build: 
      context: .
      dockerfile: ./src/Services/NotificationService/Dockerfile
    ports:
      - 7004:80
    env_file:
      - ./src/Services/NotificationService/.env
    depends_on:
      - rabbitmq
volumes:
  pgdata:
  mongodata: