apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-svc
spec:
  selector:
    matchLabels:
      app: search-svc
  template:
    metadata:
      labels:
        app: search-svc
    spec:
      containers:
      - name: search-svc
        image: karalinskidavid/microservicestestproject/search-svc:latest
        imagePullPolicy: Never
        env:
          - name: RabbitMq__Host
            valueFrom: 
              configMapKeyRef:
                name: search-configmap
                key: RabbitMq__Host
          - name: RabbitMq__User
            valueFrom:
              configMapKeyRef:
                name: search-configmap
                key: RabbitMq__User
          - name: RabbitMq__Password
            valueFrom:
              configMapKeyRef:
                name: search-configmap
                key: RabbitMq__Password
          - name: ConnectionStrings__SearchDb
            valueFrom:
              configMapKeyRef:
                name: search-configmap
                key: ConnectionStrings__SearchDb