apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-svc
spec:
  selector:
    matchLabels:
      app: notification-svc
  template:
    metadata:
      labels:
        app: notification-svc
    spec:
      containers:
      - name: notification-svc
        image: karalinskidavid/microservicestestproject/notification-svc:latest
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /hc/ready
            port: 80
        livenessProbe:
          httpGet:
            path: /hc/live
            port: 80
        env:
          - name: RabbitMq__Host
            valueFrom: 
              configMapKeyRef:
                name: notification-configmap
                key: RabbitMq__Host
          - name: RabbitMq__User
            valueFrom:
              configMapKeyRef:
                name: notification-configmap
                key: RabbitMq__User
          - name: RabbitMq__Password
            valueFrom:
              configMapKeyRef:
                name: notification-configmap
                key: RabbitMq__Password